<?php
    $this->headLink()->appendStylesheet($this->assetUrl('index.css', 'MPCustomInput'));
?>
<h1>Malaja Pereščepina Database</h1>

<div class="mp-index-panel">
<h3><a href="<?php echo $objectsLink ?>">Objekte</a></h3>
Items in Datenbank: <?php echo $objectCount ?>
</div>

<div class="mp-index-panel">
<h3><a href="<?php echo $imagesLink ?>">Bilddokumente</a></h3>
Items in Datenbank:  <?php echo $imagesCount ?>
</div>

<div class="mp-index-panel">
<h3><a href="<?php echo $textsLink ?>">Schriftdokumente</a></h3>
Items in Datenbank:  <?php echo $textsCount ?>
</div>


<div class="mp-index-panel">
<h3><a href="<?php echo $literatureLink ?>">Literatur</a></h3>
Items in Datenbank:  <?php echo $literatureCount ?>
</div>

<div class="mp-divider"></div>


<div class="mp-thesauri-list">
<h3>Concepts / Thesauri</h3>

<table>
<?php foreach ($thesauri as $thesaurus): ?>
    <tr>
        <td><?php echo $thesaurus["label"] ?></td>
        <td><a href="<?php echo $thesaurus["link"] ?>" ><?php echo $thesaurus["count"] ?></a></td>
    </tr>
<?php endforeach; ?>
</table>

</div>